INCLUDE "constants.asm"

INCLUDE "code/int.asm"
INCLUDE "code/rst.asm"
INCLUDE "code/header.asm"
INCLUDE "code/init.asm"
INCLUDE "code/alias.asm"
INCLUDE "code/joypad.asm"
INCLUDE "code/video/copy.asm"
INCLUDE "code/task.asm"
INCLUDE "code/lcd.asm"
INCLUDE "code/oam.asm"
INCLUDE "code/math.asm"
INCLUDE "code/sound.asm"
INCLUDE "code/save.asm"
